version: '2'
services:

  payments:
    build: .
    image: payments
    container_name: sky-payments
    depends_on:
      - db
    links:
      - db
    ports:
      - "9090:9090"
    environment:
      VIRTUAL_HOST: payments.local

  db:
    image: mongo:latest
    container_name: sky-payment-db
    ports:
      - "27018:27018"
    volumes:
      - ./backup:/backup:rw