version: '2'
services:

  products:
    build: .
    image: products
    container_name: sky-products
    depends_on:
      - db
    links:
      - db
    ports:
      - "8080:8080"
    environment:
      VIRTUAL_HOST: products.local

  db:
    image: mongo:latest
    container_name: sky-product-db
    ports:
      - "27018:27018"
    volumes:
      - ./backup:/backup:rw