version: '2'
services:

  users:
    build: ./User
    image: project/users
    container_name: sky-users
    depends_on:
      - db
    links:
      - db
    ports:
      - "8080:8080"
    environment:
      VIRTUAL_HOST: users.local

  db:
    image: mongo:latest
    container_name: sky-db
    ports:
      - "27017:27017"
    volumes:
      - ./backup:/backup:rw